name: Linters Verification
run-name: ${{ github.actor }} is running linters
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        linter: [mypy, pylint, flake8]
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Install Python
        run: uv python Install
      
      - name: Sync uv
        run: uv Sync

      - name: Run ${{ matrix.linter }}
        run: uv run ${{ matrix.linter }} compute_sales.py